#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

PGKMAN=npx

source .husky/helper/get_pgkman.sh

${PGKMAN} lint-staged
${PGKMAN} jest --watch=false --passWithNoTests
${PGKMAN} playwright test --project chromium
